제출 폼 수정
modern-agile-team/coko-admin pull request #29
Opened 2024-12-28 10:16 UTC by rhehfl

## 🔗 관련 이슈
#28 

## 📝작업 내용

### 1. 기존 state 를 사용하여 form을 다루었었는데 이 부분에 대해서 formData를 사용하여 값을 얻어오는 형태로 변경하였습니다.

추가로 `react-19`에 나온 form action들을 활용해보려 했으나
```ts
// Using <form> Actions and useActionState
function ChangeName({ name, setName }) {
  const [error, submitAction, isPending] = useActionState(
    async (previousState, formData) => {
      const error = await updateName(formData.get("name"));
      if (error) {
        return error;
      }
      redirect("/path");
      return null;
    },
    null,
  );

  return (
    <form action={submitAction}>
      <input type="text" name="name" />
      <button type="submit" disabled={isPending}>Update</button>
      {error && <p>{error}</p>}
    </form>
  );
}
```
기존 사용하고있던 라이브러리인 tanstack-query의 비동기 메소드들이 더 좋고 같이 쓰는건 별 의미가 없을 것 같아서 굳이 사용하지 않았습니다 ㅎㅎ;;

추가로 다음과 같은 이슈도 있어서 action이 아닌 onSubmit 이벤트를 사용하였습니다. 관련 이슈: https://github.com/facebook/react/issues/31649 

### 2. 메인 프로젝트에서 했던 것 처럼 폴더 구조도 변경시켰습니다.
어드민에서도 비슷한 환경에서 작업을 하고 싶어서 변경시켰습니다!

### 3. 약간의 에러핸들링을 추가시켰습니다.

mutate의 onError
```ts
updateQuiz(
        {
          id: prevQuiz.id,
          ...parsedQuizData,
        },
        {
          onError: error => {
            setErrorMessage(error.message);
          },
          onSuccess: () => {
            closeModal();
          },
        }
      );
```
예전에 읽은 [tkdodo mutation](https://highjoon-dev.vercel.app/blogs/12-mastering-mutations-in-react-query#%EC%9D%BC%EB%B6%80-%EC%BD%9C%EB%B0%B1%EC%9D%80-%EC%8B%A4%ED%96%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%9D%84-%EC%88%98-%EC%9E%88%EC%8A%B5%EB%8B%88%EB%8B%A4-some-callbacks-might-not-fire) 글이 생각나서 변형이 성공시켰을때만 modal 이 닫히고 만약 에러가 발생한다면 error alert를 띄우는 등의 사용자 경험을 향상 시키는 ui 작업을  mutate의 콜백에 추가하였습니다.

## 🔍 변경 사항

- [ ] form 에서 state에서 formData 활용
- [ ] 폴더구조
- [ ] 에러핸들링 추가

## 💬리뷰 요구사항 (선택사항)

2024-12-28 12:48 UTC, zzzRYT commented on src/axios/interceptor.ts
> +const responseFunction = (config: AxiosResponse<any, any>) => {
any타입은 일부로 넣어두신건가요?

2024-12-28 13:03 UTC, rhehfl commented on src/axios/interceptor.ts
> +const responseFunction = (config: AxiosResponse<any, any>) => {
```ts
export interface AxiosResponse<T = any, D = any>  {
  data: T;
  status: number;
  statusText: string;
  headers: AxiosResponseHeaders;
  config: AxiosRequestConfig<D>;
  request?: any;
}

```
과 같이 첫번째 제네릭으로 데이터타입 추론이 가능했네요 사실 큰 생각 없이 타입을 지정해놓은감이 있긴합니다..😓
![image](https://github.com/user-attachments/assets/b24e58aa-6c80-44fe-bff2-c65606cfeae5)
다만 저 제네릭은 인터셉터 부분에서 데이터 타입을 추론하기 위한 타입이기 때문에 실질적으로 데이터를 다루는 쿼리 부분에서는
![image](https://github.com/user-attachments/assets/789d3502-33eb-42ef-9f90-50a6403f8520)
과 같이 `apis`쪽에서 지정해 준 타입대로 추론이 되어서 개인적으로는 굳이 하나하나 타입을 지정해줘야 하나 싶긴 합니다!

2024-12-28 13:05 UTC, rhehfl commented on src/axios/interceptor.ts
> +const responseFunction = (config: AxiosResponse<any, any>) => {
```ts
const requestFunction = (config: InternalAxiosRequestConfig) => {
  return config;
};
const responseFunction = (config: AxiosResponse) => {
  config.data;
  return config;
};
const responseError = (error: AxiosError) => {
  if (error.response?.status) {
    const message = status[error.response.status];
    if (message) {
      error.message = message;
    }
  }
  return Promise.reject(error);
};
```
제네릭의 기본 타입이 `any` 로 지정되어있어서 위와같이 명시적으로 지정해주지 않아도 될 것 같습니다!

2024-12-28 15:13 UTC, ssi02014 commented on src/features/part/queries.ts
> +};
import 부분이랑 그 외 코드랑 문맥상 줄바꿈으로 분리해주면 좋을 것 같습니다 :)

2024-12-28 15:16 UTC, ssi02014 commented on src/features/quiz/queries.ts
> +export default quizzesQueries;
```suggestion
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import quizzesApis from './apis';
import { Quiz, QuizFilters } from './types';

const quizKeys = {
  all: ['quizzes'] as const,
  lists: () => [...quizKeys.all, 'list'] as const,
  list: (filters?: QuizFilters) => [...quizKeys.lists(), filters] as const,
};

const quizzesQueries = {
  read: (params: QuizFilters) => {
    return useQuery<Quiz[]>({
      queryKey: quizKeys.lists(),
      queryFn: () => quizzesApis.get(),
      select: quizzes => {
        const { partId, sectionId } = params;
        return quizzes.filter(quiz => {
          const matchesSection =
            sectionId === 0 || quiz.sectionId === sectionId;
          const matchesPart = partId === 0 || quiz.partId === partId;
          return matchesSection && matchesPart;
        });
      },
    });
  },
  create: () => {
    const queryClient = useQueryClient();
    return useMutation({
      mutationFn: quizzesApis.post,
      onSuccess: () => {
        queryClient.invalidateQueries({
          queryKey: quizKeys.lists(),
        });
      },
    });
  },
  update: () => {
    const queryClient = useQueryClient();
    return useMutation({
      mutationFn: quizzesApis.put,
      onSuccess: () => {
        queryClient.invalidateQueries({
          queryKey: quizKeys.lists(),
        });
      },
    });
  },
  delete: () => {
    const queryClient = useQueryClient();

    return useMutation({
      mutationFn: quizzesApis.delete,
      onSuccess: () => {
        queryClient.invalidateQueries({
          queryKey: quizKeys.lists(),
        });
      },
    });
  },
};

export default quizzesQueries;
```

2024-12-28 15:17 UTC, ssi02014 commented on src/features/quiz/types.ts
> +}
```suggestion
export type Category =
  | 'COMBINATION'
  | 'MULTIPLE_CHOICE'
  | 'OX_SELECTOR'
  | 'SHORT_ANSWER';
  
export interface Quiz {
  id: number;
  partId: Part['id'];
  sectionId: Section['id'];
  title: string;
  question: string;
  answer: string[];
  category: Category;
  answerChoice: string[];
}
```

2024-12-28 15:19 UTC, ssi02014 commented on src/features/quiz/ui/QuizForm.tsx
> +    validCategories.includes(selectedCategory ?? '');
```suggestion
export function QuizForm({ prevQuiz, closeModal, mod }: QuizFormProps) {
  const [selectedCategory, setSelectedCategory] = useState<Category>();
  const [errorMessage, setErrorMessage] = useState('');
  
  const { data: parts } = partsQueries.read();
  const { mutate: createQuiz } = quizzesQueries.create();
  const { mutate: updateQuiz } = quizzesQueries.update();
  
  const handleMutate = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const quizData = Object.fromEntries(formData.entries());
    const parsedQuizData = parseQuizData(quizData);

    if (mod === 'create') {
      createQuiz(parsedQuizData, {
        onError: error => {
          setErrorMessage(error.message);
        },
        onSuccess: () => {
          closeModal();
        },
      });
    } else if (mod === 'update' && prevQuiz) {
      updateQuiz(
        {
          id: prevQuiz.id,
          ...parsedQuizData,
        },
        {
          onError: error => {
            setErrorMessage(error.message);
          },
          onSuccess: () => {
            closeModal();
          },
        }
      );
    }
  };
  
  const validCategories = ['COMBINATION', 'MULTIPLE_CHOICE'];
  const isChoiceRequired =
    validCategories.includes(prevQuiz?.category ?? '') ||
    validCategories.includes(selectedCategory ?? '');
```
state면 state, query면 query로 그룹화해서 관리하면 가독성이 높아지며, 코드 추적이 쉽습니다.

2024-12-28 15:20 UTC, ssi02014 commented on src/features/quiz/ui/QuizForm.tsx
> +  const validCategories = ['COMBINATION', 'MULTIPLE_CHOICE'];
해당 코드는 컴포넌트 밖에다 상수로서 선언해주는 것은 어떨까요? 이런 상수들은 컴포넌트 라이프타임에 영향을 주지 않는게 좋습니다.

2024-12-28 15:22 UTC, ssi02014 requested changes, later dismissed
코드의 목적과 관심사에 맞게 그룹화하고, 문맥에 맞게 줄바꿈으로 분리해주세요.
가독성과 코드의 추적이 원활해집니다ㅎㅎ~!!

2024-12-28 15:22 UTC, ssi02014 commented on src/axios/interceptor.ts
> +};
```suggestion
const status = {
  400: '데이터필드를 확인해주세용',
  404: '페이지를 찾을 수 없습니다.',
  500: '서버 오류가 발생했습니다.',
} as const;
```
as const로 관리는 힘든걸까요?

2024-12-28 15:26 UTC, ssi02014 commented on src/features/quiz/service/parseQuizData.ts
> +};
이전 utils와 types와 같은 맥락으로 utils로 관리하면 어떨까요?

2024-12-28 15:28 UTC, ssi02014 commented on src/features/section/service/parseSectionData.ts
> +): Omit<Section, 'id' | 'sectionId'> => {
section의 더 디테일한 타입이 가능 할 것 같은데 디테일하게 타입 정의가 어떨까요?

2024-12-28 15:33 UTC, ssi02014 commented on src/pages/Quiz.tsx
> +        closeEvent={() => setQuiz(undefined)}
```suggestion
        closeEvent={() => setQuiz(null)}
```
undefined와 null의 차이를 혹시 아실까요?

2024-12-28 15:35 UTC, ssi02014 commented on src/features/part/service/parsePartData.ts
> +};
part의 타입을 더 명확한 타입으로 정의할 수 있을 것 같습니다. 이미 정의된 Part 타입이 존재하는 것으로 확인됩니다.
```ts
export interface Part {
  id: number;
  sectionId: number;
  name: string;
}
```

2024-12-28 15:53 UTC, bluetree7878 commented
@rhehfl 
계속해서 어드민 업데이트를 해주셔서 감사합니다! 😊
덕분에 데이터베이스를 편하게 관리할 수 있었어요. ㅎㅎ

저희 coko-front처럼 import 할 때 절대경로 설정하는 거 어떠신가요?? 리뷰할 때도 보기 편할 것 같아요.

```json
// tsconfig.app.json 
{
  "compilerOptions": {
    "paths": {
      "@/*": ["*"],
      "@axios": ["axios"],
      "@hooks*": ["hooks/*"],
      "@features*": ["features/*"],
      "@pages*": ["pages/*"],
      "@common*": ["common/*"],
    },
  }
}
```

2024-12-28 16:07 UTC, rhehfl commented
@bluetree7878 리뷰 감사합니다! 
절대경로 부분은 694d5fae3f1e29d33da2d98fd2be6eeb195a8016 커밋에서 작업해놓았습니다 아직 백엔드 api가 작업중이여서 추후에 PR 올리도록 하겠습니다👍

2024-12-28 16:23 UTC, rhehfl commented on src/features/quiz/service/parseQuizData.ts
> +};
>이전에 논의했던 feature/{feature}/types와 같은 맥락으로 utils.ts로 관리하면 어떨까요?

좋은 것 같습니다!

@ssi02014 quiz 인자의 경우에는 
![image](https://github.com/user-attachments/assets/8e6f269a-e898-4795-b1ea-977efa9a3293)
다음과같이 formData에서 값을 추출 할 경우에 `FormDataEntryValue`로 추론되어 이 값을 제가 원하는 `Quiz`타입으로 변환시키기 위한 역할을 합니다. 따라서 인자를 Quiz 타입으로 제한시키는 것 보다는 다음과 같은 형태로 변경하는건 어떨까요...?
```ts
export const isString = (value: FormDataEntryValue): value is string => {
  return typeof value === 'string';
};

export const parseQuizData = (
  quiz: Record<string, FormDataEntryValue>
): Omit<Quiz, 'id' | 'sectionId'> => {
  return {
    title: quiz.title.toString(),
    category: quiz.category as Category,
    partId: Number(quiz.partId),
    question: quiz.question.toString(),
    answer: isString(quiz.answer) ? quiz.answer.split(',') : [],
    answerChoice: isString(quiz.answerChoice)
      ? quiz.answerChoice.split(',')
      : [],
  };
};

```
인자의 타입이 `any`에서 `FormDataEntryValue` 으로 축소되어 이전보다는 타입 안정성이 올라갈 것 같습니다!

2024-12-28 16:27 UTC, rhehfl commented on src/features/section/service/parseSectionData.ts
> +): Omit<Section, 'id' | 'sectionId'> => {
```ts
Omit<Section, 'id' | 'sectionId'>
```
타입 부분은 제가 실수를 한 것 같습니다 😓
```ts
Omit<Section, 'id'>
```
타입입니다!
section 인자의 타입 같은 경우는 Record<string, FormDataEntryValue>타입이 조금 더 디테일 할 것 같아요!

2024-12-28 16:30 UTC, rhehfl commented on src/features/quiz/service/parseQuizData.ts
> +};
다시 생각해보니 그러면 인자의 네이밍도 quiz가 아닌 그냥 formData 같은것이 조금 더 적절했을 것 같아요😓

2024-12-28 16:35 UTC, rhehfl commented on src/pages/Quiz.tsx
> +        closeEvent={() => setQuiz(undefined)}
아이고.. 보통 의도적으로 비워놓을땐 null을 많이 사용하는데 제대로 생각하지 않고 코드를 짠 것 같습니다 😢

2024-12-28 16:41 UTC, rhehfl commented
@ssi02014 리뷰 감사합니다! 코드 가독성에 대해 많이 생각해보게 되는 리뷰였습니다.

>코드의 목적과 관심사에 맞게 그룹화하고, 문맥에 맞게 줄바꿈으로 분리해주세요.
가독성과 코드의 추적이 원활해집니다ㅎㅎ~!!

이 말처럼  [d48903b](https://github.com/modern-agile-team/coko-admin/pull/29/commits/d48903ba14746a7cbf434c68d9d0a90e215aee44) 커밋에서 수정하였습니다 !!
항상 리뷰 봐주셔서 감사합니다 😢

2024-12-28 16:47 UTC, ssi02014 commented on src/features/quiz/service/parseQuizData.ts
> +};
아하 그렇군요 ~ 말씀처럼 네이밍을 변경하는게 좋겠다는 생각이 들었네요 :) quizFormData 뭐 이런 네이밍은 어떨까 생각이드네요 ! 다른 함수들도 마찬가지 sectionFormData ~!

2024-12-28 16:51 UTC, rhehfl commented on src/features/quiz/service/parseQuizData.ts
> +};
넵 좋은 것 같습니다 !

2024-12-28 16:53 UTC, ssi02014 commented on src/features/quiz/queries.ts
> +  },
```suggestion
  read: (params: QuizFilters) => {
    return useQuery<Quiz[]>({
      queryKey: quizKeys.lists(),
      queryFn: () => quizzesApis.get(),
      select: quizzes => {
        const { partId, sectionId } = params;
        return quizzes.filter(quiz => {
          const matchesSection =
            sectionId === 0 || quiz.sectionId === sectionId;
          const matchesPart = partId === 0 || quiz.partId === partId;
          return matchesSection && matchesPart;
        });
      },
    });
  },

  create: () => {
    const queryClient = useQueryClient();
    return useMutation({
      mutationFn: quizzesApis.post,
      onSuccess: () => {
        queryClient.invalidateQueries({
          queryKey: quizKeys.lists(),
        });
      },
    });
  },
```
ㅋㅋㅋ헉! 제가 약간의 오해를 드린 것 같습니다 ㅋㅋㅋㅋ 객체의 프로퍼티까지 줄바꿈으로 굳이 나누지는 않아도 됩니다 ㅎㅎㅎㅎㅎ

2024-12-28 16:57 UTC, ssi02014 commented on src/features/section/queries.ts
> +export default sectionsQueries;
```suggestion
import { useQuery, useQueryClient, useMutation } from '@tanstack/react-query';
import sectionsApis from './apis';

const sectionKeys = {
  all: ['sections'] as const,
  lists: () => [...sectionKeys.all, 'list'] as const,
};

const sectionsQueries = {
  read: () => {
    return useQuery({
      queryKey: sectionKeys.lists(),
      queryFn: () => sectionsApis.get(),
    });
  },
  create: () => {
    const queryClient = useQueryClient();
    return useMutation({
      mutationFn: sectionsApis.post,
      onSuccess: () => {
        queryClient.invalidateQueries({
          queryKey: sectionKeys.lists(),
        });
      },
    });
  },
  delete: () => {
    const queryClient = useQueryClient();
    return useMutation({
      mutationFn: sectionsApis.delete,
      onSuccess: () => {
        queryClient.invalidateQueries({
          queryKey: sectionKeys.lists(),
        });
      },
    });
  },
  
};

export default sectionsQueries;
```
이런 코드들이 import, key 객체, query 객체, export 부분 4영역으로 분리되어야 합니다 ㅎㅎㅎ

2024-12-28 16:59 UTC, ssi02014 commented on src/features/section/ui/SectionForm.tsx
> +  };
```suggestion
  const handleMutate = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    
    const formData = new FormData(e.currentTarget);
    const sectionData = Object.fromEntries(formData.entries());
    const parsedSectionData = parseSectionData(sectionData);
    
    createMutate(parsedSectionData, {
      onSuccess: () => {
        closeModal();
      },
      onError: error => {
        setErrorMessage(error.message);
      },
    });
  };
```

2024-12-28 17:46 UTC, rhehfl commented on src/features/quiz/queries.ts
> +  },
아이고 ㅎㅎ;; 감사합니다!😢

2024-12-29 10:47 UTC, bluetree7878 approved these changes

2024-12-30 01:14 UTC, merged